#!/usr/bin/env python3
"""Emit the firmware-independent Rust SHARC+ decoder table.

The input is the public-manual-derived ``decode_table.json``.  The generated
module intentionally contains only decode facts (form id, width, masks,
priority and field layout); it never reads a firmware image, loader metadata,
or generated symbol table.  Runtime code supplies its own symbol interner.

Run from the repository root:

    python3 tools/sharc_decode_rsgen.py
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = ROOT / "tools" / "sharcspec" / "decode_table.json"
DEFAULT_OUTPUT = ROOT / "native" / "sharc" / "src" / "decode_table.rs"


def form_id(name: str) -> str:
    return re.sub(r"\s*\((\w+)\)", r"_\1", re.sub(r"^Type", "", name))


def leading_fixed_bits(mask: int) -> int:
    return next((47 - bit for bit in range(47, -1, -1) if not mask >> bit & 1), 48)


def rust_string(text: str) -> str:
    return json.dumps(text)


def runtime_fields(fields: list[dict]) -> list[dict]:
    """Match sharc_rsgen.split_compute for the runtime `Insn` seam."""
    result = []
    for field in fields:
        if field["label"] == "compute":
            assert (field["hi"], field["lo"]) == (22, 0)
            result.append(field)
            result.extend(
                (
                    {"label": "compute[22:16]", "hi": 22, "lo": 16},
                    {"label": "compute[15:0]", "hi": 15, "lo": 0},
                )
            )
        else:
            result.append(field)
    return result


def render(payload: dict) -> str:
    forms = []
    for row in payload["forms"]:
        # ``visa`` is the variable-width decoder's existing form set.  This
        # generator decodes every member of that set; execution policy belongs
        # to the core, not to this firmware-independent table.
        if not row["visa"]:
            continue
        mask = int(row["mask"], 16)
        fields = ", ".join(
            "FieldSpec { key: %s, stem: %s, hi: %d, lo: %d }"
            % (
                rust_string(field["label"]),
                rust_string(field["label"].split("[", 1)[0]),
                field["hi"],
                field["lo"],
            )
            for field in runtime_fields(row["fields"])
        )
        forms.append(
            "    Form { name: %s, width_bytes: %d, mask: 0x%012x, value: 0x%012x, "
            "leading_fixed_bits: %d, fixed_bits: %d, kind: %s, fields: &[%s] },"
            % (
                rust_string(form_id(row["name"])),
                row["width"] // 8,
                mask,
                int(row["value"], 16),
                leading_fixed_bits(mask),
                row["fixed_bits"],
                "DecodeKind::Uncertain"
                if row.get("unconfirmed_bits", 0)
                else "DecodeKind::Confident",
                fields,
            )
        )
    return """// @generated by tools/sharc_decode_rsgen.py from tools/sharcspec/decode_table.json.
// Public ISA decode facts only; do not hand-edit.

pub(super) static FORMS: &[Form] = &[
%s
];
""" % "\n".join(forms)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    payload = json.loads(args.input.read_text())
    args.output.write_text(render(payload))


if __name__ == "__main__":
    main()
